export const ar = {
  header: {
    promoText: "احصل على خصم 10٪ على طلبك الأول باستخدام الرمز",
    code: "جديد!",
    dresses: "الفساتين",
    tops: "القمصان",
    occasion: "فساتين المناسبات",
    kids: "مجموعة الأطفال",
    home: "أليينا هوم",
    shopAll: "تسوق الكل",
    account: "الحساب",
    search: "بحث",
    cart: "السلة",
  },
  banner: {
    freeReturns: "إرجاع مجاني",
    fastDelivery: "توصيل سريع ومجاني",
    finestFabrics: "أجود الأقمشة",
  },
  product: {
    buyNow: "اشتري الآن",
    addToCart: "أضف إلى السلة",
    promoText:
      "للحصول على خصم 10٪ على طلبك الأول ولفترة محدودة فقط استخدم الرمز:",
    deliveryWithin: "التوصيل خلال 1-2 يوم عمل إلى",
    freeReturn: "إرجاع مجاني",
    inKSA: "في المملكة العربية السعودية خلال 7 أيام من التسليم",
  },
  productDetails: {
    materialDetails: "تفاصيل المواد",
    cleaningInstructions: "تعليمات التنظيف",
    description: "الوصف",
    freeReplacementReturn: "الاستبدال والإرجاع المجاني",
    stretch: "المطاطية",
    lining: "البطانة",
    fabricDetail: "تفاصيل القماش",
    noStretch: "بدون مطاطية",
    mediumStretch: "مطاطية متوسطة",
    highStretch: "مطاطية عالية",
    noLining: "بدون بطانة",
    lined: "مبطن",
    crepe: "كريب",
    doNotBleach: "لا تستخدم المبيض",
    ironLowTemp: "الكي بدرجة حرارة منخفضة إذا لزم الأمر",
    saudiArabia: "المملكة العربية السعودية",
    restOfWorld: "بقية العالم",
    freeReturnText:
      "يمكنك طلب إرجاع مجاني داخل المملكة العربية السعودية حتى 7 أيام بعد استلام طلبك",
    freeDeliveryText: "توصيل مجاني للطلبات التي تزيد عن 400 ريال سعودي",
    noRefundText:
      "منتجات أليينا للملابس المشتراة خلال العروض والخصومات غير قابلة للاسترداد تحت أي ظرف من الظروف.",
    riyadh: "الرياض",
    dammam: "الدمام",
    jeddah: "جدة",
    otherCities: "مدن أخرى",
    deliveryTime: "التوصيل خلال {{value}} يوم عمل",
    descriptionText:
      "انغمسي في الأناقة الفاخرة مع فستاني الميدي من الكريب بكتف مكشوف. يتميز بتصميم كتف مكشوف جذاب ومصنوع من قماش كريب عالي الجودة، يفوح هذا الفستان بالرقي والتميز. مثالي لأي مناسبة، سيكون خيارك المفضل للأناقة السهلة والسحر الأنيق.",
    buyWholeSet: "اشتري المجموعة كاملة",
    viewItem: "عرض العنصر",
  },
  relatedProducts: {
    title: "قد يعجبك أيضًا",
    newArrival: "وصل حديثاً",
  },
} as const;
