export const en = {
  header: {
    promoText: "Get 10% off your first order with code",
    code: "NEW!",
    dresses: "Dresses",
    tops: "Tops",
    occasion: "Occasion dresses",
    kids: "Kids Collection",
    home: "Aleena Home",
    shopAll: "Shop All",
    account: "Account",
    search: "Search",
    cart: "Cart",
  },
  banner: {
    freeReturns: "Free Returns",
    fastDelivery: "Fast & Free Delivery",
    finestFabrics: "Finest Fabrics",
  },
  product: {
    buyNow: "Buy it Now",
    addToCart: "Add to Cart",
    promoText:
      "For a 10% off of your first order and for a limited time only use code:",
    deliveryWithin: "Delivery within 1-2 business days to",
    freeReturn: "free return",
    inKSA: "in KSA within 7 days of delivery",
  },
  productDetails: {
    materialDetails: "Material Details",
    cleaningInstructions: "Cleaning Instructions",
    description: "Description",
    freeReplacementReturn: "Free Replacement and Return",
    stretch: "Stretch",
    lining: "Lining",
    fabricDetail: "Fabric Detail",
    noStretch: "No Stretch",
    mediumStretch: "Medium Stretch",
    highStretch: "High Stretch",
    noLining: "No Lining",
    lined: "Lined",
    crepe: "Crepe",
    doNotBleach: "Do not use bleach",
    ironLowTemp: "Iron at a low temperature if needed",
    saudiArabia: "Saudi Arabia",
    restOfWorld: "Rest of The World",
    freeReturnText:
      "You can request a free return within Saudi Arabia up to 7 days after receiving your order",
    freeDeliveryText: "Free delivery for orders over 400 SAR",
    noRefundText:
      "Aleena clothing products purchased during offers and discounts are not refundable under any circumstances.",
    riyadh: "Riyadh",
    dammam: "Dammam",
    jeddah: "Jeddah",
    otherCities: "Other Cities",
    deliveryTime: `Delivery with {{value}} business days`,
    descraption: "Descraption",
    descriptionText:
      "Indulge in luxurious elegance with our Bare shoulder Crepe Midi dress. Featuring a flattering bare shoulder design and crafted from high-quality crepe fabric, this dress exudes sophistication and exclusivity. Perfect for any occasion, it will be your go-to choice for effortless style and graceful charm.",
    buyWholeSet: "Buy the whole set",
    viewItem: "View Item",
  },
  relatedProducts: {
    title: "You may also like",
    newArrival: "New Arrival",
  },
} as const;
